name: Deploy Astro site to Pages

on:
  push:
    branches: ["master", "main"]   # works whether your default is master or main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Installs deps, builds, and uploads the Pages artifact for you.
      - name: Install, build, and upload
        uses: withastro/action@v2
        with:
          node-version: 20                    # default is 20; set 22 if you want
          package-manager: npm@latest         # force npm so pnpm is never used
          path: .                             # change to subfolder (e.g., apps/blog)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
